import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { EthersConnectButton } from '@/Button'
import Transaction from '@/Transaction'
import Block from '@/Block'

const tokens = [
  {
    address: "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619",
    chain: "Polygon"
  },
  {
    address: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    chain: "Mainnet"
  },
] as const

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <EthersConnectButton/>
        {tokens.map(data=>(<Transaction key={data.chain} {...data} />))}
        <Block/>
      </main>
    </>
  )
}
